import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#ffffff",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  hero: {
    background: "linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)",
    padding: "80px 24px 120px",
    textAlign: "center",
    position: "relative",
    overflow: "hidden",
  },
  heroContent: {
    maxWidth: "900px",
    margin: "0 auto",
    position: "relative",
    zIndex: 10,
  },
  heroBadge: {
    display: "inline-block",
    padding: "6px 16px",
    backgroundColor: "#f0f9ff",
    color: "#0284c7",
    borderRadius: "20px",
    fontSize: "14px",
    fontWeight: 600,
    marginBottom: "24px",
    border: "1px solid #bae6fd",
  },
  heroTitle: {
    fontSize: "72px",
    fontWeight: 800,
    lineHeight: 1.1,
    margin: "0 0 24px 0",
    color: "#0f172a",
    letterSpacing: "-0.03em",
  },
  heroGradient: {
    background:
      "linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #d946ef 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  heroSubtitle: {
    fontSize: "20px",
    lineHeight: 1.6,
    color: "#64748b",
    margin: "0 auto 40px",
    maxWidth: "600px",
  },
  heroButtons: {
    display: "flex",
    gap: "16px",
    justifyContent: "center",
    flexWrap: "wrap" as const,
  },
  heroPrimary: {
    padding: "16px 32px",
    backgroundColor: "#0f172a",
    color: "#ffffff",
    border: "none",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 4px 14px rgba(0, 0, 0, 0.15)",
  },
  heroSecondary: {
    padding: "16px 32px",
    backgroundColor: "transparent",
    color: "#0f172a",
    border: "2px solid #e2e8f0",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  features: {
    padding: "80px 24px",
    backgroundColor: "#ffffff",
  },
  featuresGrid: {
    maxWidth: "1200px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "32px",
  },
  featureCard: {
    textAlign: "center",
    padding: "32px 24px",
  },
  featureIcon: {
    fontSize: "48px",
    marginBottom: "16px",
  },
  featureTitle: {
    fontSize: "20px",
    fontWeight: 700,
    color: "#0f172a",
    margin: "0 0 8px 0",
  },
  featureText: {
    fontSize: "15px",
    color: "#64748b",
    lineHeight: 1.6,
    margin: 0,
  },
  interactive: {
    padding: "80px 24px",
    backgroundColor: "#f8fafc",
  },
  interactiveTitle: {
    fontSize: "48px",
    fontWeight: 800,
    textAlign: "center",
    color: "#0f172a",
    margin: "0 0 12px 0",
    letterSpacing: "-0.02em",
  },
  interactiveSubtitle: {
    fontSize: "18px",
    textAlign: "center",
    color: "#64748b",
    margin: "0 0 48px 0",
  },
  tabs: {
    display: "flex",
    justifyContent: "center",
    gap: "8px",
    marginBottom: "48px",
    flexWrap: "wrap" as const,
  },
  tab: {
    padding: "12px 24px",
    backgroundColor: "transparent",
    color: "#64748b",
    border: "1px solid #e2e8f0",
    borderRadius: "10px",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  tabActive: {
    backgroundColor: "#0f172a",
    color: "#ffffff",
    borderColor: "#0f172a",
  },
  tabContent: {
    maxWidth: "1400px",
    margin: "0 auto",
  },
  moduleSection: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "48px",
    marginBottom: "48px",
  },
  moduleDemo: {
    position: "sticky" as const,
    top: "24px",
    alignSelf: "start",
  },
  demoCard: {
    backgroundColor: "#ffffff",
    borderRadius: "16px",
    padding: "32px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05), 0 10px 40px rgba(0, 0, 0, 0.05)",
    border: "1px solid #e2e8f0",
  },
  demoHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
  },
  demoTitle: {
    fontSize: "24px",
    fontWeight: 700,
    color: "#0f172a",
    margin: 0,
  },
  demoBadge: {
    padding: "6px 12px",
    backgroundColor: "#f0fdf4",
    color: "#16a34a",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: 600,
    border: "1px solid #bbf7d0",
  },
  demoStats: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "32px",
  },
  statBox: {
    padding: "24px",
    backgroundColor: "#f8fafc",
    borderRadius: "12px",
    textAlign: "center",
    border: "1px solid #e2e8f0",
  },
  statLabel: {
    fontSize: "13px",
    color: "#64748b",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    marginBottom: "8px",
  },
  statValue: {
    fontSize: "36px",
    fontWeight: 800,
    color: "#0f172a",
  },
  demoActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
  },
  actionButton: {
    padding: "14px 20px",
    backgroundColor: "#0f172a",
    color: "#ffffff",
    border: "none",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  actionButtonDanger: {
    padding: "14px 20px",
    backgroundColor: "#fef2f2",
    color: "#dc2626",
    border: "1px solid #fecaca",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  badgeShowcase: {
    marginBottom: "24px",
  },
  unlockButton: {
    width: "100%",
    padding: "16px",
    backgroundColor: "#6366f1",
    color: "#ffffff",
    border: "none",
    borderRadius: "10px",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  questsContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },
  leaderboardContainer: {
    marginTop: "24px",
  },
  moduleCode: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "24px",
  },
  codeTitle: {
    fontSize: "20px",
    fontWeight: 700,
    color: "#0f172a",
    margin: "0 0 8px 0",
  },
  codeBlock: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  codeLabel: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#6366f1",
    marginBottom: "12px",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },
  codeSnippet: {
    backgroundColor: "#0f172a",
    color: "#e2e8f0",
    padding: "16px",
    borderRadius: "8px",
    fontSize: "13px",
    fontFamily: 'Monaco, "Courier New", monospace',
    overflow: "auto",
    margin: 0,
    lineHeight: 1.6,
  },
  codePreview: {
    marginTop: "16px",
    padding: "16px",
    backgroundColor: "#f8fafc",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
  },
  footer: {
    backgroundColor: "#0f172a",
    padding: "48px 24px",
  },
  footerContent: {
    maxWidth: "1200px",
    margin: "0 auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: "24px",
  },
  footerBrand: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  footerLogo: {
    fontSize: "24px",
    fontWeight: 800,
    color: "#ffffff",
    margin: 0,
  },
  footerTagline: {
    fontSize: "14px",
    color: "#94a3b8",
    margin: 0,
  },
  footerLinks: {
    display: "flex",
    gap: "24px",
    alignItems: "center",
  },
  footerLink: {
    color: "#94a3b8",
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: 500,
    transition: "color 0.2s",
  },
  footerVersion: {
    padding: "4px 12px",
    backgroundColor: "#1e293b",
    color: "#94a3b8",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: 600,
  },
};
